### ISSUE TITLE
WeMOS pinouts

### ISSUE THREAD

**Issue by mdhiggins** [mdhiggins/ESP8266-HTTP-IR-Blaster#124]
The default pinouts do not work on certain WeMOS devices, most commonly the D1 Mini
The configpin in particular does not work

If we can crowd source a list of working pinouts I'll add an alternative blueprint option for WeMOS devices

WeMOS users please share what pin configuration you're using

**Comment by jonathanhickford** [comment]
I'm using a WeMOS D1 Mini (v2.3.0). I've not tried using multiple IR receivers, but the below work for me. 
```
const int pinr1 = D3;       // Receiving pin (Arduino GPIO0)
const int pins1 = D4;       // Transmitting preset 1 (GPIO2)
const int configpin = D2;   // Config pin (GPIO4)
```
In an ideal WeMOS world the config pin would perhaps be D3 (which is one used on the 1 button shield), but I had problems using that as the config pin.

**Comment by vkhurana** [comment]
@jonathanhickford i tried this with my wemos, and it seems like the IR LED is always on? It only seems to go off when the wemos LED comes on. Can you share the circuit diagram you used? I'm using the one from readme, but adapted for Wemos D1.

**Comment by jonathanhickford** [comment]
It was pretty much as the circuit diagram. I used the 5V output for the R2 -> IR LED -> collector.

**Comment by lowtolerance** [comment]
D4 is what I used originally for transmission, and I couldn't figure out why it caused the LED to be so much dimmer than the same circuit hooked up to a NodeMCU on the same pin. Turns out that D4 is what the NodeMCU uses for it's onboard LED, and it already has a 10k resistor tied to that pin, so you end up with too much resistance on the line for full output. The blaster WILL work on this pin, but I had to place it within a couple of inches of the receiver on my TV for it to detect the signal, and the TV wouldn't detect most signals output by the blaster.

D3 and D8 also have a 10k resistor, leaving D0-D2 + D5-D7 as the most sensible choices for IO (see https://wiki.wemos.cc/products:d1:d1_mini). Personally, I'm using GPIO 14 for receiving and GPIO 12 (D5 and D6, respectively) for receiving, which seems to be doing fine, although I haven't had a lot of time to play with my IR blaster since I switched the pins I'm using for it.

**Comment by jonathanhickford** [comment]
Thanks. I'm now trying the below, however like @vkhurana I'm finding the LED remains on all the time.
```
const int pinr1 = D5;        // Receiving pin (GPIO14)
const int pins1 = D6;        // Transmitting preset 1 (GPIO12)
const int configpin = D2;    // Reset Pin (GPIO4)
```

UPDATE: Turns out I'd been sent a mixed bag of transistors and was using the wrong one...

**Comment by vkhurana** [comment]
@jonathanhickford maybe i have the same issue - you're using a 2N222?

**Comment by jonathanhickford** [comment]
Yep 2N222 now - and the resistor values and LED as per the readme. That resolved my problem.

**Comment by mdhiggins** [comment]
Are you guys just eliminating the configuration for S2-S4 or just leaving them at default and not using them? Gonna try and add this to the wiki page for future users

**Comment by lowtolerance** [comment]
I’ve just been leaving the unused declarations at their default values. Might not be a bad idea to be able to enable/disable the additional transmitters through a simple Boolean, but it’s hardly necessary.

**Comment by jebbett** [comment]
const int pinr1 = 14;                                         // Receiving pin (D5)
const int pins1 = 4;                                          // Transmitting preset 1 (D2)
const int configpin = 3;                                   // Reset Pin (RX)

I've got a couple of D1 Minis using the above config, shame there isn't somewhere for people to upload their projects.. The mini has a nice prototype shield that's idea for this and keeps it tiny, I have one with IR leds built in and one using a Samsung Smart TV IR Blaster BN96-31644A, which consists of 5 IR LEDs pointing each in different directions, all in parallel.. giving 360x180 degree coverage..

Edit, here's a link to the two I have built: [Pic](http://hyttioaoa.co.uk/wp/wp-content/uploads/2018/03/IR-Wemos-MiniD1.png)
