### ISSUE TITLE
Great project (thanks) but skill restricted in Australia

### ISSUE THREAD

**Issue by upiw** [mdhiggins/ESP8266-HTTP-IR-Blaster#150]
Manage this Skill
You are not eligible to enable this skill due to geographical restrictions.

Any ideas how to get this working if you have an Aussie account?

**Comment by mdhiggins** [comment]
This is a limitation imposed by Amazon and out of my control unfortunately. I will expand to each region as they make it available

**Comment by mdhiggins** [comment]
Looks like amazon only recently opened up support for Australia

I’ll make some updates and submit it for approval

From: upiw
Sent: Sunday, February 18, 2018 6:21 PM
To: mdhiggins/ESP8266-HTTP-IR-Blaster
Cc: Subscribed
Subject: [mdhiggins/ESP8266-HTTP-IR-Blaster] Great project (thanks) but skillrestricted in Australia (#150)

Manage this Skill
You are not eligible to enable this skill due to geographical restrictions.
Any ideas how to get this working if you have an Aussie account?

**Comment by upiw** [comment]
You are so kind.  Thanks so much.
I really appreciate all the effort you have put in for folks trying to build this project.

Regards,

Upi (AUS)

**Comment by mdhiggins** [comment]
Submitted. Pending review by Amazon

**Comment by mdhiggins** [comment]
Approved. Should be live now give it a shot

**Comment by upiw** [comment]
Thanks heaps Michael.
