### ISSUE TITLE
Change input does not work

### ISSUE THREAD

**Issue by sunilammanabrolu** [mdhiggins/ESP8266-HTTP-IR-Blaster#173]
Change input of <device> to HDMI 3 on Alexa returns "something went wrong"
It was working last week

**Comment by mdhiggins** [comment]
It appears amazon has broken things, all the requests are erroring out before they are even forwarded to the skill

Made a post here if you want to follow along
https://forums.developer.amazon.com/questions/168419/inputcontroller-suddenly-broken.html

Haven't seen a single input request actually get sent to the skill since 5/2 0300 UTC so that's probably when they made whatever change and broke things

**Comment by mdhiggins** [comment]
Looks like they fixed it spontaneously
Working for you now?

**Comment by sunilammanabrolu** [comment]
Working now. Thanks
