### ISSUE TITLE
Unable to do port forwarding

### ISSUE THREAD

**Issue by nairsatheesh** [mdhiggins/ESP8266-HTTP-IR-Blaster#276]
Hi Michael,

IM facing this issue for quite sometime i have put the code everything is fine but the ESP 8266 is not communicating with the Alexa
When im trying to use port 667 Im unable to open the Gateway 192.168.0.107 which i had assigned to esp8266
It is only working on Port 80
Any tutorial for  Port forwarding will be great
16:06:52.930 -> *WM: IP Address:
16:06:52.930 -> *WM: 192.168.0.107
16:06:52.930 -> WiFi connected! User chose hostname 'Irblaster' passcode 'Pass' and port '667'
16:06:52.930 -> *WM: freeing allocated params!
16:06:52.930 -> WiFi configuration complete
16:06:52.930 -> Local IP: 192.168.0.107
16:06:52.930 -> URL to send commands: http://Irblaster.local:667
16:06:52.930 -> ArduinoOTA started
16:06:52.930 -> MDNS http service added. Hostname is set to Irblaster.local:667
16:06:52.930 -> HTTP Server started on port 667
16:06:52.930 -> Starting UDP
16:06:52.930 -> Local port: 8888
16:06:52.930 -> Waiting for sync
16:06:52.930 -> Transmit NTP Request
16:06:52.977 -> time.google.com: 216.239.35.12
16:06:53.071 -> Receive NTP Response
16:06:53.352 -> External IP: 
16:06:53.352 -> External IP address request took 267 ms
16:06:53.352 -> No errors detected with security configuration
16:06:53.352 -> EPOCH time obtained for security checks
16:06:53.352 -> Ready to send and receive IR signals
16:06:54.899 -> Turning off the LED to save power.
With port 667 not able to open dashboard after adding the dashboard

**Comment by nairsatheesh** [comment]
and one more thing i would like to add the ESP8266 server only opens up on port 80 i tried on 443 or 667 im unable to open anything on that and  serial monitor doens't give any error aswell

**Comment by TheMCMan** [comment]
What is the make and model of your internet router?

**Comment by nairsatheesh** [comment]
Thank you so much for replying
It's TPLINK WR841N

**Comment by TheMCMan** [comment]
Hi there,. Looks like we have a bit of a time difference : ). I'm in California..

Here is a port forwarding instructional for your router : )

https://www.cfos.de/en-us/cfos-personal-net/port-forwarding/tp-link-tl-wr841n.htm

**Comment by nairsatheesh** [comment]
let me check that today

**Comment by TheMCMan** [comment]
Hi There,

Thought I'd dive in here a bit more deeply...

Just want to setup some definitions and concepts before we really get started.

Gateway = Internet Router = TPLINK WR841N = most likely 192.168.0.1
IRBlaster = ESP8266 = 192.168.0.107
IRBlster Port = 667

To get started.. you need to confirm your network setup state.

Let's clarify your actual gateway address..
If you are using a Windows machine, you can confirm your network gateway IP address.
https://www.groovypost.com/howto/find-windows-10-device-ip-address/
Does your pc say it is using 192.168.0.1 as the gateway?

Next, let's see if your IRBlaster is really assigned 192.168.0.107..
For this, I find a network scanner to work best..
I use a freeware application called Advanced IP scanner.
If your gateway is actually 192.168.0.1
and your subnet mask is 255.255.255.0
Then your network scan range is 192.168.0.1-192.168.0.255

Concept..  Port forwarding is only needed when you access your internal network from a separate and different network..

Say your computer has IP address 192.168.106 and the IRBlaster is on 192.168.107:667..
To access IRBaster from your computer, in Chrome you only need to enter 192.168.107:667 and there would not be any port forwarding involved at all for this to work..

On the other-hand, if you try to access your network by using your public IP address..
(Find your public IP address by typing in "What is My IP" into google) your internet router needs to know the port number of your internal device (IRBlaster,) in order to deliver the internet traffic to the correct device on your network.

The main use for port forwarding, is when you get traffic on your network that is not a direct response.  For example, when you surf the internet, your computer sends a request to view a page.  The website responds directly to your computer as the internet router sees the packet of information is a response to your computer's webpage request.  So your internet router directs this traffic to your computer.

However when you use Alexa, for instance, she gets your action phrase, sends it to an Amazon server for processing, Amazon servers convert the action phrase into a command.  Then sends this command to your IRBlaster address.  So, since the IRBlaster did not initiate the command command request, your internet router, does not know how to handle the traffic directed at the IRBlaster. 

Port forwarding is therefore the traffic assistant that allows independent communication to different devices on your network.

As a background.. Port forwarding is needed because you only have 1 publicly facing IP address.  But maybe you have 10 different network devices...  If your internet provider gave your 10 different publicly facing IP address, then you would not need port forwarding.

This is just like regular paper mail that comes to your house.  Except at home, you are the Mail Gateway.  All the letters come to your home in 1 box.  You collect the mail, you then give the letters addressed to Bob, and Jane separately, and keep your nairsatheesh mail.  You have literally done packet forwarding at this point.  Just change the names to numbers and you have snail mail port forwarding.  For instance, Bob could be port 667...  On the other-hand, if Bob had a message for Jane in your house, Bob could just give this message directly to Jane without using the postmaster. 
 
Sorry for getting long winded... port forwarding is a difficult concept to grasp.  The bottom line is... i think port forwarding is not the issue...   maybe an authentican issue to get a WiFi DHCP address...

This sounds similar to your issue...
[https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/214](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/214)
could you post the full log like this person did please?


I've made about 5 of these now : )  For me and friends... : )

**Comment by nairsatheesh** [comment]
sure I will

**Comment by nairsatheesh** [comment]
And thank you for helping me

**Comment by nairsatheesh** [comment]
Few question before I try again
Should I use ESP8266 board version 2.4.0 ?or should the later version?
Im only able to access the 192.168.0.107 on port 80 If add any other port for eg 667,443 on the WIFI setup page it shows its connected on serial monitor however unable to open the gateway(192.168.0.107) sorry for bothering you:)

**Comment by mdhiggins** [comment]
You are specifying the custom port when you try to access it correct? 80 is the default port so if you don't specify the port but you're using 80 everything works, if you switch to anything else, you have to include that in your address

**Comment by TheMCMan** [comment]
so in chrome surf over to http://192.168.0.107:667 and see if it works..

**Comment by TheMCMan** [comment]
Hey there nairsatheesh,  no bother at all.  no worries.. hope you get it working : )

The Board Manager Library Installs the ESP8266 Arduino Board Core:

As of Feb 11, 2020, most current version is ESP8266 board v2.6.3.  
Upgraded to this version on Feb 11.
Did not work after ESP8266 rebooted

Trying ESP8266 board v2.6.2.  Upgraded to this version on Feb 11.
Did not work after ESP8266 rebooted

Trying ESP8266 board v2.6.1.  Upgraded to this version on Feb 11.
Worked after rebooting ESP8266

Hope this helps..

**Comment by nairsatheesh** [comment]
Hi michael,
something weird is happening her on the board in spite of flashing the raw code which you have put on the pagenow its not taking me to to the network configuration page. its not allowing to enter the wifi set up page now when i put 192.168.0.107 its taking me directly there 
so ideally it should have taken me to the WIFI setup page it is not happeing this issue started happening since today and one more new thing i would like to show you 
![Uploading image.png…]()

![serialmonitor](https://user-images.githubusercontent.com/61969761/78407863-68a81400-7623-11ea-883f-39c27ea458de.PNG)

**Comment by nairsatheesh** [comment]
![arduinopage1](https://user-images.githubusercontent.com/61969761/78408225-2df2ab80-7624-11ea-9e97-f95f1a935d0b.PNG)

**Comment by mdhiggins** [comment]
Your settings are stored in the SPIFFS filesystem and are not erased by a reflash. To get back to the configuration page you need to set the config pin to ground which is outline in the readme

https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster#force-wifi-reconfiguration

**Comment by mdhiggins** [comment]
Since I can see you're on windows, open command prompt and post your `ipconfig` output too so we can get an idea if you have your network setup correct for your router

**Comment by nairsatheesh** [comment]
> 
> 
> Since I can see you're on windows, open command prompt and post your `ipconfig` output too so we can get an idea if you have your network setup correct for your router

![image](https://user-images.githubusercontent.com/61969761/78408681-5fb84200-7625-11ea-8c4b-7a8aae7f2a16.png)

**Comment by mdhiggins** [comment]
Alright yeah so that's good
192.168.0.107 is fine for your ESP8266
Gateway and DNS should be 192.168.0.1
Subnet should be 255.255.255.0

Port should be fine. Did you clarify if you were specifying the port in the address when trying to access it when it was set to something other than 80?

**Comment by nairsatheesh** [comment]
> 
> 
> Alright yeah so that's good
> 192.168.0.107 is fine for your ESP8266
> Gateway and DNS should be 192.168.0.1
> Subnet should be 255.255.255.0
> 
> Port should be fine. Did you clarify if you were specifying the port in the address when trying to access it when it was set to something other than 80?


im trying to reflash it to wifi mode forgive me im still in learning phase to my understanding "Set GPIO10 to ground to force a WiFi configuration reset" meaning to connect jumper from GND to GPIO10Correct?
![gpio](https://user-images.githubusercontent.com/61969761/78409366-1ff25a00-7627-11ea-90a1-99c95b694b6c.PNG)

**Comment by mdhiggins** [comment]
Exactly. It has to be set to ground on boot.

**Comment by nairsatheesh** [comment]
Nothing is happening after reboot
So should I upload the code again
In this setup

**Comment by mdhiggins** [comment]
Uploading code again won’t help and isn’t required. Some unofficial NodeMCU models don’t support setting GPIO10 to ground so you might need to modify the configPin in the blueprint to another pin. 

The LianLi V3 for example is one that doesn’t support GPIO10 setting to ground

**Comment by nairsatheesh** [comment]
I flashed using a blank bin files and node mcu pyflasher gone to the
configuration mode
😊

**Comment by nairsatheesh** [comment]
I have open the interface on port 667 success now the next thing is port
forwarding 😵
For which I will refer to ur explanation

**Comment by nairsatheesh** [comment]
I have still doing port forwarding once you are awake just message me if you can help me step by step on my router
Im able to open the page on 192.168.0.107:667 on local network

**Comment by mdhiggins** [comment]
You just need to access your router settings now and forward port 667 to 192.168.0.107

https://www.cfos.de/en-us/cfos-personal-net/port-forwarding/tp-link-tl-wr841n.htm

Service Port and Internal Port - 667
IP Address - 192.168.0.107
Protocol - TCP
Status - Enabled

**Comment by nairsatheesh** [comment]
I have done that now how to test this if it's working or not

**Comment by nairsatheesh** [comment]
I have got this following error on the alexa skill

**Comment by mdhiggins** [comment]
You didn't post an error or give any information to allow us to help you

**Comment by nairsatheesh** [comment]
sure i had attached the error give me sometime i will send it

**Comment by nairsatheesh** [comment]
![Screenshot_20200404-221952](https://user-images.githubusercontent.com/61969761/78456664-94c6a200-76c2-11ea-9fab-cb8b63f21d28.jpg)

**Comment by mdhiggins** [comment]
Now it’s probably something to do with your amazon userID not being set correctly, the time code not working correctly. One thing you can do is post the home page screenshot of the irblaster including the footer text most importantly (blur your external IP). The other would be to privately email me your json output at the bottom of tehpsyc.pythonanywhere.com and let me see if you’ve formatted that correctly.

**Comment by nairsatheesh** [comment]
if you don't mind can you provide me ur email address I will send you that details 
as I will send you the details of the serail monitor output

**Comment by nairsatheesh** [comment]
Hi Mike

here is the serial monitor details
00:59:58.996 -> WiFi connected! User chose hostname 'IRblaster' passcode 'pass' and port '667'
00:59:58.996 -> *WM: freeing allocated params!
00:59:58.996 -> WiFi configuration complete
00:59:59.030 -> Local IP: 192.168.0.107
00:59:59.030 -> URL to send commands: http://IRblaster.local:667
00:59:59.030 -> ArduinoOTA started
00:59:59.030 -> MDNS http service added. Hostname is set to IRblaster.local:667
00:59:59.030 -> HTTP Server started on port 667
00:59:59.030 -> Starting UDP
00:59:59.030 -> Local port: 8888
00:59:59.030 -> Waiting for sync
00:59:59.030 -> Transmit NTP Request
00:59:59.030 -> time.google.com: 216.239.35.8
00:59:59.167 -> Receive NTP Response
00:59:59.613 -> External IP: 
00:59:59.613 -> External IP address request took 461 ms
00:59:59.613 -> No errors detected with security configuration
00:59:59.613 -> EPOCH time obtained for security checks
00:59:59.648 -> Ready to send and receive IR signals
01:00:00.992 -> Turning off the LED to save power.
![dashboard](https://user-images.githubusercontent.com/61969761/78459929-5b9a2c00-76da-11ea-864c-9ac2ef60bd68.png)

**Comment by mdhiggins** [comment]
mdhiggins23 @ gmail.com
