### ISSUE TITLE
How do you store wifi config ?

### ISSUE THREAD

**Issue by nikki-reprap** [mdhiggins/ESP8266-HTTP-IR-Blaster#62]
Every time i reboot i need to reenter my wifi config how do i store it ?

Thanks Nikki

**Comment by jfette** [comment]
+1 - I'm having the same problem with Wifi with the latest code.

**Comment by THEP0PE** [comment]
I am having the same problem as well. Also, after every time I enter my wifi information and allow the board to reboot, my wifi router's interface becomes unavailable. I have had to reboot the router every time in order to regain access to it. The wifi stays up and running, I just can't access the interface to view what devices are connected. Using Linksys EA6400.

**Comment by mdhiggins** [comment]
Please see this already closed issue
https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster/issues/58
