### ISSUE TITLE
control with openhab

### ISSUE THREAD

**Issue by saikhurana** [mdhiggins/ESP8266-HTTP-IR-Blaster#68]
hey i just wanted to as if anyone has ever integrated this with openhab using http binding. i was able to control this through webhook but not directly on the local server. the openhab spits out some authentication error 
HTTP/1.1 401 Unauthorized
i want to control it directly with my openhab server. 
also i want to request the writer of this code to make this with mqtt protocall.

**Comment by mdhiggins** [comment]
No plans to do MQTT or further integration with other service, the large complex multistep commands don’t play nice with MQTT since they contain a lot of data. Also the ESP8266 has authentication issues with AWS IOT devices making this project not ideal for that

There’s going to be a new Alexa skill that adds native smart home commands to the device though using the V3 version of their API. Its already approved and will be published once Amazon opens up V3 to consumers at the end of the month, letting you control your devices using natural language and not depend on IFTTT/Trigger

**Comment by mdhiggins** [comment]
If you're interested in beta testing the new skill prior to release let me know

**Comment by saikhurana** [comment]
i really wish i could beta test this sketch but i have no knowledge about amazon echo skills(the coding part). if you can teach me i can beta test :-)

**Comment by mdhiggins** [comment]
You actually need no coding knowledge at all, that's the beauty of the new skill!

Email me your amazon account email address and I'll add you as a beta tester (mdhiggins23@gmail.com)

**Comment by saikhurana** [comment]
Done!!Check Your Inbox
