### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by GeeBee93** [mdhiggins/ESP8266-HTTP-IR-Blaster#81]
Hi!

I guess this is more a general question instead of a specific issue. I found your little project through reddit and it sounds awesome, thank you!

I was walking through your tutorial and I got some headache after I read that step:
Forward whichever port your ESP8266 web server is running on so that it can be accessed from outside your local network, this is critical since Alexa commands come from Amazon's servers, not locally

Is that a normal behaviour you need to do for each smart home device with Alexa? I've already got some Sonoff devices with Tasmota, do I need to publish them to the WWW aswell to be available for Alexa?

If I really need to do that I will return my Echo's as soon as they arrive tomorrow. I am not going to publish everything to web. 

Thank you! :)

Sebastian

**Comment by mdhiggins** [comment]
Not every device needs to be published to the web, commercial devices with push notifications or devices than run using MQTT and an intermediate broker do not usually need an open port but those solutions weren’t feasible with this DIY project. 

There are security measures in place since this project does require an open port - see the readme for more information.

You can also use services use as Smartthings or homeassistant to act as an intermediate
